version: '3.9'

services:
  master:
    image: postgres:15.6-alpine
    environment:
      - POSTGRES_PASSWORD=super_secret_password
      - POSTGRES_USER=postgres
    ports:
      - target: 5432
        published: 5566
        protocol: tcp
        mode: host
    volumes:
      - some-shop-pg-data:/var/lib/postgresql/data
      - some-shop-pg-backup-data:/tmp-backup
    networks:
      main-overlay-net:
        aliases:
          - some-shop-pg
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname==internal-worker-2
      labels:
        - 'traefik.enable=false'
        # swarm-utils.backup
        - 'swarm-utils.backup.enable=true'
        - 'swarm-utils.backup.exec=pg_dump -U postgres some_shop_db_name | gzip > /tmp-backup/pg_dump.sql.gz'
        - 'swarm-utils.backup.exec.shell=/bin/sh'
        - 'swarm-utils.backup.stop=true'
        - 'swarm-utils.backup.volume-list-upload=some-shop-pg-backup-data'
        - 'swarm-utils.backup.volume-list-upload.s3.url=s3-api.domain.com'
        - 'swarm-utils.backup.volume-list-upload.s3.https=true'
        - 'swarm-utils.backup.volume-list-upload.s3.access-key=...'
        - 'swarm-utils.backup.volume-list-upload.s3.secret-key=...'
        - 'swarm-utils.backup.volume-list-upload.s3.bucket=some_bucket_name'
        - 'swarm-utils.backup.volume-list-upload.s3.retention-days=8'
        - 'swarm-utils.backup.token=aaasssddd333'

volumes:
  some-shop-pg-data:
    external: true
  some-shop-pg-backup-data:
    external: true

networks:
  main-overlay-net:
    external: true
